[build]
target = "./src-ui/index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
address = "127.0.0.1"
port = 1420
open = false

[[hooks]]
stage = "build"
command = "bash"
command_arguments = ["-c", "sass ./src-ui/styles.scss | tailwindcss -c ./src-ui/tailwind.config.js -i - -o $TRUNK_STAGING_DIR/styles.css"]
