#[path = "audio/input.rs"]
pub mod audio_input;
#[path = "audio/params.rs"]
pub mod audio_params;
#[path = "audio/perform.rs"]
pub mod audio_perform;
#[path = "audio/record.rs"]
pub mod audio_record;
#[path = "audio/speaker.rs"]
pub mod audio_speaker;
pub mod auth;
#[path = "auto-complete.rs"]
pub mod auto_complete;
pub mod avatar;
#[path = "chat/error.rs"]
pub mod chat_list_error;
#[path = "chat/item.rs"]
pub mod chat_list_item;
#[path = "chat/responder.rs"]
pub mod chat_list_responder;
#[path = "chat/speaker.rs"]
pub mod chat_list_speaker;
#[path = "chat/params.rs"]
pub mod chat_params;
#[path = "chat/record.rs"]
pub mod chat_record;
pub mod dropdown;
#[path = "error-warning.rs"]
pub mod error_warning;
#[path = "file-upload.rs"]
pub mod file_upload;
#[path = "image/list.rs"]
pub mod image_list;
#[path = "image/params.rs"]
pub mod image_params;
#[path = "image/responding.rs"]
pub mod image_responding;
#[path = "img-edit/input.rs"]
pub mod img_edit_input;
#[path = "img-edit/params.rs"]
pub mod img_edit_params;
#[path = "img-edit/perform.rs"]
pub mod img_edit_perform;
#[path = "img-edit/record.rs"]
pub mod img_edit_record;
#[path = "img-edit/speaker.rs"]
pub mod img_edit_speaker;
#[path = "img-gen/params.rs"]
pub mod img_gen_params;
#[path = "img-gen/perform.rs"]
pub mod img_gen_perform;
#[path = "img-gen/record.rs"]
pub mod img_gen_record;
#[path = "img-gen/speaker.rs"]
pub mod img_gen_speaker;
#[path = "img-var/input.rs"]
pub mod img_var_input;
#[path = "img-var/params.rs"]
pub mod img_var_params;
#[path = "img-var/perform.rs"]
pub mod img_var_perform;
#[path = "img-var/record.rs"]
pub mod img_var_record;
#[path = "img-var/speaker.rs"]
pub mod img_var_speaker;
pub mod loading;
pub mod mask;
#[path = "not-found.rs"]
pub mod not_found;
pub mod prompt;
#[path = "prompt-speaker.rs"]
pub mod prompt_speaker;
pub mod proxy;
#[path = "topic/filter.rs"]
pub mod topic_filter;
#[path = "topic/item.rs"]
pub mod topic_item;
#[path = "topic/list.rs"]
pub mod topic_list;
