#[path = "audio-transcript.rs"]
pub mod audio_transcript;
#[path = "audio-translate.rs"]
pub mod audio_translate;
pub mod chat;
pub mod home;
#[path = "img-edit.rs"]
pub mod img_edit;
#[path = "img-gen.rs"]
pub mod img_gen;
#[path = "img-var.rs"]
pub mod img_var;
pub mod sidebar;
#[path = "topic-create.rs"]
pub mod topic_create;
