pub mod auth;
pub mod cancel;
#[path = "chat-pause.rs"]
pub mod chat_pause;
pub mod chatgpt;
pub mod confirm;
pub mod copy;
pub mod edit;
#[path = "edit-off.rs"]
pub mod edit_off;
pub mod empty;
pub mod enter;
pub mod error;
#[path = "error-warning.rs"]
pub mod error_warning;
pub mod filter;
#[path = "filter-off.rs"]
pub mod filter_off;
pub mod home;
#[path = "home-up.rs"]
pub mod home_up;
#[path = "image-broken.rs"]
pub mod image_broken;
#[path = "image-editing.rs"]
pub mod image_editing;
pub mod left;
pub mod loading;
pub mod menu;
#[path = "not-found.rs"]
pub mod not_found;
pub mod plus;
#[path = "prompt-send.rs"]
pub mod prompt_send;
#[path = "prompt-setting.rs"]
pub mod prompt_setting;
pub mod proxy;
pub mod refresh;
pub mod right;
pub mod save;
pub mod search;
pub mod selector;
pub mod trans;
#[path = "trans-error.rs"]
pub mod trans_error;
pub mod trash;
pub mod upload;
#[path = "zoom-in.rs"]
pub mod zoom_in;
#[path = "zoom-out.rs"]
pub mod zoom_out;
